routes/web.php
<?php

use App\Http\Controllers\App\BookmarkletController;
use App\Http\Controllers\App\DashboardController;
use App\Http\Controllers\App\ExportController;
use App\Http\Controllers\App\FeedController;
use App\Http\Controllers\App\ImportController;
use App\Http\Controllers\App\SearchController;
use App\Http\Controllers\App\SystemSettingsController;
use App\Http\Controllers\App\TrashController;
use App\Http\Controllers\App\UserSettingsController;
use App\Http\Controllers\CronController;
use App\Http\Controllers\FetchController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\Guest\FeedController as GuestFeedController;
use App\Http\Controllers\Guest\LinkController as GuestLinkController;
use App\Http\Controllers\Guest\ListController as GuestListController;
use App\Http\Controllers\Guest\TagController as GuestTagController;
use App\Http\Controllers\Models\LinkController;
use App\Http\Controllers\Models\ListController;
use App\Http\Controllers\Models\NoteController;
use App\Http\Controllers\Models\TagController;
use App\Http\Controllers\Setup\AccountController;
use App\Http\Controllers\Setup\DatabaseController;
use App\Http\Controllers\Setup\MetaController;
use App\Http\Controllers\Setup\RequirementsController;
use Illuminate\Support\Facades\Route;
use Rap2hpoutre\LaravelLogViewer\LogViewerController;

// Frontpage
Route::get('/', FrontController::class)->name('front');

// Setup routes
Route::get('setup/start', [MetaController::class, 'welcome'])
    ->name('setup.welcome');
Route::get('setup/requirements', [RequirementsController::class, 'index'])
    ->name('setup.requirements');
Route::get('setup/database', [DatabaseController::class, 'index'])
    ->name('setup.database');
Route::post('setup/database', [DatabaseController::class, 'configure'])
    ->name('setup.save-database');
Route::get('setup/account', [AccountController::class, 'index'])
    ->name('setup.account');
Route::post('setup/account', [AccountController::class, 'register'])
    ->name('setup.save-account');
Route::get('setup/complete', [MetaController::class, 'complete'])
    ->name('setup.complete');

// Bookmarklet routes
Route::prefix('bookmarklet')->group(function () {
    Route::get('add', [BookmarkletController::class, 'getLinkAddForm'])->name('bookmarklet-add');
    Route::get('show', [BookmarkletController::class, 'getCompleteView'])->name('bookmarklet-complete');
    Route::get('login', [BookmarkletController::class, 'getLoginForm'])->name('bookmarklet-login');
});

Route::get('cron/{token}', CronController::class)->name('cron');

Route::group(['middleware' => 'auth:api'], function () {
    Route::get('links/feed', [FeedController::class, 'links'])->name('links.feed');
    Route::get('lists/feed', [FeedController::class, 'lists'])->name('lists.feed');
    Route::get('lists/{list}/feed', [FeedController::class, 'listLinks'])->name('lists.links.feed');
    Route::get('tags/feed', [FeedController::class, 'tags'])->name('tags.feed');
    Route::get('tags/{tag}/feed', [FeedController::class, 'tagLinks'])->name('tags.links.feed');
});

// Model routes
Route::group(['middleware' => ['auth']], function () {
    Route::get('dashboard', [DashboardController::class, 'index'])
        ->name('dashboard');

    Route::resource('links', LinkController::class);
    Route::resource('lists', ListController::class);
    Route::resource('tags', TagController::class);
    Route::resource('notes', NoteController::class)
        ->except(['index', 'show', 'create']);

    Route::post('links/toggle-check/{link}', [LinkController::class, 'updateCheckToggle'])
        ->name('links.toggle-check');
    Route::post('links/mark-working/{link}', [LinkController::class, 'markWorking'])
        ->name('links.mark-working');

    Route::get('search', [SearchController::class, 'getSearch'])
        ->name('get-search');
    Route::post('search', [SearchController::class, 'doSearch'])
        ->name('do-search');

    Route::get('import', [ImportController::class, 'getImport'])
        ->name('get-import');
    Route::post('import', [ImportController::class, 'doImport'])
        ->name('do-import');

    Route::get('export', [ExportController::class, 'getExport'])
        ->name('get-export');
    Route::post('export/html', [ExportController::class, 'doHtmlExport'])
        ->name('do-html-export');
    Route::post('export/csv', [ExportController::class, 'doCsvExport'])
        ->name('do-csv-export');

    Route::get('trash', [TrashController::class, 'index'])
        ->name('get-trash');
    Route::post('trash/clear', [TrashController::class, 'clearTrash'])
        ->name('clear-trash');
    Route::post('trash/restore', [TrashController::class, 'restoreEntry'])
        ->name('trash-restore');

    Route::get('settings', [UserSettingsController::class, 'getUserSettings'])
        ->name('get-usersettings');
    Route::post('settings/account', [UserSettingsController::class, 'saveAccountSettings'])
        ->name('save-settings-account');
    Route::post('settings/app', [UserSettingsController::class, 'saveAppSettings'])
        ->name('save-settings-app');
    Route::post('settings/change-password', [UserSettingsController::class, 'changeUserPassword'])
        ->name('change-user-password');
    Route::post('settings/generate-api-token', [UserSettingsController::class, 'generateApiToken'])
        ->name('generate-api-token');

    Route::get('settings/system', [SystemSettingsController::class, 'getSystemSettings'])
        ->name('get-systemsettings');
    Route::post('settings/system', [SystemSettingsController::class, 'saveSystemSettings'])
        ->name('save-settings-system');
    Route::post('settings/generate-cron-token', [SystemSettingsController::class, 'generateCronToken'])
        ->name('generate-cron-token');

    Route::post('fetch/tags', [FetchController::class, 'getTags'])
        ->name('fetch-tags');
    Route::post('fetch/lists', [FetchController::class, 'getLists'])
        ->name('fetch-lists');
    Route::post('fetch/existing-links', [FetchController::class, 'searchExistingUrls'])
        ->name('fetch-existing-links');
    Route::post('fetch/html-for-url', [FetchController::class, 'htmlForUrl'])
        ->name('fetch-html-for-url');
    Route::get('fetch/update-check', [FetchController::class, 'checkForUpdates'])
        ->name('fetch-update-check');

    Route::get('system/logs', [LogViewerController::class, 'index'])
        ->name('system-logs');
});

// Guest access routes
Route::prefix('guest')->middleware(['guestaccess'])->group(function () {

    Route::get('links/feed', [GuestFeedController::class, 'links'])->name('guest.links.feed');
    Route::get('lists/feed', [GuestFeedController::class, 'lists'])->name('guest.lists.feed');
    Route::get('lists/{list}/feed', [GuestFeedController::class, 'listLinks'])->name('guest.lists.links.feed');
    Route::get('tags/feed', [GuestFeedController::class, 'tags'])->name('guest.tags.feed');
    Route::get('tags/{tag}/feed', [GuestFeedController::class, 'tagLinks'])->name('guest.tags.links.feed');

    Route::resource('links', GuestLinkController::class)
        ->only(['index'])
        ->names([
            'index' => 'guest.links.index',
        ]);

    Route::resource('lists', GuestListController::class)
        ->only(['index', 'show'])
        ->names([
            'index' => 'guest.lists.index',
            'show' => 'guest.lists.show',
        ]);

    Route::resource('tags', GuestTagController::class)
        ->only(['index', 'show'])
        ->names([
            'index' => 'guest.tags.index',
            'show' => 'guest.tags.show',
        ]);
});

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')

    <h3 class="mb-4">@lang('user.hello', ['user' => auth()->user()->name])</h3>

    <div class="row">
        <div class="col-12 col-md-7">

            <div class="card">
                <div class="card-header">
                    @lang('link.add_quick')
                </div>
                <div class="card-body">

                    <form action="{{ route('links.store') }}" method="POST">
                        @csrf

                        <input type="hidden" name="is_private" value="{{ usersettings('private_default') ?: 0 }}">
                        <input type="hidden" name="title" value="">
                        <input type="hidden" name="description" value="">
                        <input type="hidden" name="lists" value="">
                        <input type="hidden" name="tags" value="">

                        <div class="input-group">
                            <input type="url" id="url" name="url" required
                                class="form-control{{ $errors->has('url') ? ' is-invalid' : '' }}"
                                placeholder="@lang('link.url')" value="{{ old('url') }}"
                                aria-label="@lang('link.url')">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">
                                    <x-icon.plus class="mr-2"/> @lang('linkace.add')
                                </button>
                            </div>
                        </div>

                        @if ($errors->has('url'))
                            <p class="invalid-feedback" role="alert">
                                {{ $errors->first('url') }}
                            </p>
                        @endif

                    </form>

                </div>
            </div>

        </div>
        <div class="col-12 col-md-5">

            <div class="card">
                <div class="card-header">
                    @lang('search.search')
                </div>
                <div class="card-body">

                    <form action="{{ route('do-search') }}" method="POST">
                        @csrf
                        <input type="hidden" name="search_title" value="on">
                        <input type="hidden" name="search_description" value="on">

                        <div class="input-group">
                            <input type="text" name="query" id="query" autofocus
                                class="form-control" placeholder="@lang('search.query')">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">
                                    <x-icon.search class="mr-2"/>
                                    @lang('search.search')
                                </button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>

        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-7">

            <div class="card mt-4">
                <div class="card-header">
                    @lang('link.recent_links')
                </div>

                <ul class="list-group list-group-flush">
                    @forelse($recent_links as $link)
                        <a href="{{ route('links.show', [$link->id]) }}"
                            class="list-group-item list-group-item-action one-line">
                            {!! $link->getIcon('mr-1') !!}
                            {{ $link->title }}
                        </a>
                    @empty
                        <li class="list-group-item text-danger">
                            @lang('linkace.no_results_found', ['model' => trans('link.links')])
                        </li>
                    @endforelse
                </ul>
            </div>

        </div>
        <div class="col-12 col-md-5">

            <div class="card mt-4">
                <div class="card-header">
                    @lang('stats.stats')
                </div>

                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <div class="d-flex align-items-center">
                            <span class="mr-1">@lang('stats.total_links')</span>
                            <span class="badge badge-secondary ml-auto">{{ $stats['total_links'] }}</span>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="d-flex align-items-center">
                            <span class="mr-1">@lang('stats.total_lists')</span>
                            <span class="badge badge-secondary ml-auto">{{ $stats['total_lists'] }}</span>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="d-flex align-items-center">
                            <span class="mr-1">@lang('stats.total_tags')</span>
                            <span class="badge badge-secondary ml-auto">{{ $stats['total_tags'] }}</span>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="d-flex align-items-center">
                            <span class="mr-1">@lang('stats.total_notes')</span>
                            <span class="badge badge-secondary ml-auto">{{ $stats['total_notes'] }}</span>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="d-flex align-items-center">
                            <span class="mr-1">@lang('stats.total_broken_links')</span>
                            <form action="{{ route('do-search') }}" method="post" class="d-inline-block ml-auto">
                                @csrf
                                <input type="hidden" name="broken_only" value="on">
                                <button type="submit"
                                    class="badge border-0 {{ $stats['total_broken_links'] > 0 ? 'badge-danger' : 'badge-secondary' }}">
                                    {{ $stats['total_broken_links'] }}
                                </button>
                            </form>
                        </div>
                    </li>
                </ul>
            </div>

        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-7">

            <div class="card mt-4">
                <div class="card-header">
                    @lang('list.recent_lists')
                </div>

                <div class="card-body">
                    @forelse($recent_lists as $list)
                        <a href="{{ route('lists.show', [$list->id]) }}" class="badge badge-light badge-lg">
                            {{ $list->name }}
                        </a>
                    @empty
                        <div class="text-danger">
                            @lang('linkace.no_results_found', ['model' => trans('list.lists')])
                        </div>
                    @endforelse
                </div>
            </div>

        </div>
        <div class="col-12 col-md-5">

            <div class="card mt-4">
                <div class="card-header">
                    @lang('tag.recent_tags')
                </div>

                <div class="card-body">
                    @forelse($recent_tags as $tag)
                        <a href="{{ route('tags.show', [$tag->id]) }}" class="badge badge-light badge-lg">
                            {{ $tag->name }}
                        </a>
                    @empty
                        <div class="text-danger">
                            @lang('linkace.no_results_found', ['model' => trans('tag.tags')])
                        </div>
                    @endforelse
                </div>
            </div>

        </div>
    </div>

@endsection